# Example configuration file for the server

# ETH
ETH_RPC_URL: "http://localhost:8545" # http://" + SERVER + ":" + PORT
ETH_CORE_ACCOUNT_PRIV: "dbcec79f3490a6d5d162ca2064661b85c40c93672968bfbd906b952e38c3e8de" # address: 0x85b427C84731bC077BA5A365771D2b64c5250Ac8

# DB
# You can use full path or just the file name to imply current path.
DB_FILE_PATH: "bridge.db"

# BTC
BTC_RPC_SERVER: "127.0.0.1"
BTC_RPC_PORT: "19001"
BTC_RPC_USERNAME: "admin1"
BTC_RPC_PWD: "123"
BTC_CHAIN_CONFIG: "regtest" # mainnet, testnet
BTC_CORE_ACCOUNT_PRIV: "cUWcwxzt2LiTxQCkQ8FKw67gd2NuuZ182LpX9uazB93JLZmwakBP" # bridge's private key
BTC_CORE_ACCOUNT_ADDR: "mvqq54khZQta7zDqFGoyN7BVK7Li4Xwnih" # bridge's address

# HTTP
HTTP_IP: "0.0.0.0" # server listens on ...
HTTP_PORT: "8080"